kind: PersistentVolume
apiVersion: v1
metadata:
  name: myapp-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100M
  hostPath:
    path: /tmp/myapp-pv
  persistentVolumeReclaimPolicy: Delete
