kind: Deployment
apiVersion: apps/v1
metadata:
  name: webster-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webster-app
  template:
    metadata:
      labels:
        app: webster-app
    spec:
      containers:
      - image: bilalmir135/webster:v1
        name: container1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate

