kind: CronJob
apiVersion: batch/v1beta1
metadata:
  name: cj
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: cjexample
        spec:
          containers:
          - name: cjcontainer
            image: docker/whalesay
            command: ["cowsay","CronJobexample"]
          restartPolicy: Never
