kind: Pod
apiVersion: v1
metadata:
  name: podcmenv
  labels:
    app: envcmexample
spec:
  containers:
  - name: container1
    image: aamirpinger/node-app-image
    ports:
    - containerPort: 8080
    imagePullPolicy: IfNotPresent
    envFrom:
    - configMapRef:
        name: cm-from-envfile
