kind: Pod
apiVersion: v1
metadata:
  name: podwithsecret
spec:
  volumes:
  - name: secret-vol
    secret:
      secretName: myfirstsecret
  containers:
  - name: container1
    image: nginx
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: secret-vol
      mountPath: /data

