kind: Pod
apiVersion: v1
metadata:
  name: podwithnodeselector
spec:
  nodeSelector:
    typeofharddisk: ssd
  containers:
  - name: container1
    image: aamirpinger/flag:latest
    ports:
    - containerPort: 80

