kind: Pod
apiVersion: v1
metadata:
  name: pv-pod
spec:
  volumes:
  - name: pv-vol
    persistentVolumeClaim:
      claimName: pvc
  containers:
  - name: container1
    image: aamirpinger/logfile_nodejs
    volumeMounts:
    - name: pv-vol
      mountPath: /data
