kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100M
  hostPath:
    path: /temp/pvexample
  persistentVolumeReclaimPolicy: Delete
